export const REQUEST_GAME = 'REQUEST_GAME';
export const RECEIVE_GAME = 'RECEIVE_GAME';
export const REQUEST_ANSWER = 'REQUEST_ANSWER';
export const RECEIVE_ANSWER = 'RECEIVE_ANSWER';
export const REQUEST_QUESTION = 'REQUEST_QUESTION';
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION';
export const RESET_GAME = 'RESET_GAME';
